/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    markets: Market;
    pages: Page;
    faqs: Faq;
    deals: Deal;
    'site-settings': SiteSetting;
    'buyer-signups': BuyerSignup;
    'deal-interest': DealInterest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    markets: MarketsSelect<false> | MarketsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'buyer-signups': BuyerSignupsSelect<false> | BuyerSignupsSelect<true>;
    'deal-interest': DealInterestSelect<false> | DealInterestSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * Private by default. Public media routes must require this value plus a published page/public deal reference check.
   */
  accessPolicy: 'private' | 'public_after_reference_check';
  /**
   * Draft/hidden/archived media is never public, even if referenced by a public page or deal.
   */
  mediaStatus: 'draft' | 'ready' | 'hidden' | 'archived';
  /**
   * If true, public media helpers deny delivery regardless of page/deal visibility.
   */
  containsExactAddressOrPrivateDetails?: boolean | null;
  /**
   * Editorial traceability only. Public serving still validates the current page/deal visibility at request time.
   */
  referencedBy?:
    | (
        | {
            relationTo: 'pages';
            value: number | Page;
          }
        | {
            relationTo: 'deals';
            value: number | Deal;
          }
        | {
            relationTo: 'faqs';
            value: number | Faq;
          }
        | {
            relationTo: 'site-settings';
            value: number | SiteSetting;
          }
      )[]
    | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  surface: 'seller' | 'buyer' | 'shared';
  status: 'draft' | 'published' | 'archived';
  summary?: string | null;
  /**
   * Baseline CMS-managed page sections. Slice 4/5 can map these to final components.
   */
  sections?:
    | {
        sectionType: 'hero' | 'rich_text' | 'cta' | 'two_column' | 'legal' | 'faq_embed' | 'deals_embed';
        eyebrow?: string | null;
        heading?: string | null;
        body?: string | null;
        image?: (number | null) | Media;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  navigation?: {
    showInNav?: boolean | null;
    navLabel?: string | null;
    sortOrder?: number | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  /**
   * URL path segment. Spaces/case are normalized automatically, e.g. "Test Deal" becomes "test-deal".
   */
  slug: string;
  /**
   * Best investment use for buyers (multi-select). Drives the deal badges and buyer filtering.
   */
  bestUse?:
    | ('fix_and_flip' | 'buy_and_hold' | 'brrrr' | 'turnkey_immediate_equity' | 'land_bank' | 'development')[]
    | null;
  /**
   * Internal-only deals must remain Hidden. Public deal visibility is websiteVisibility = public plus the approved deal status matrix.
   */
  websiteVisibility: 'hidden' | 'preview' | 'public' | 'archived';
  dealStatus: 'draft' | 'coming_soon' | 'available' | 'under_contract' | 'sold' | 'cancelled';
  /**
   * Select or create the market. Default South Florida markets are seeded by migration.
   */
  market?: (number | null) | Market;
  /**
   * Area / neighborhood label safe for public display (no exact address).
   */
  area?: string | null;
  city?: string | null;
  county?: string | null;
  zip?: string | null;
  /**
   * Default false. Exact street addresses are sensitive and public deal helpers expose exactAddress only when this is true.
   */
  showExactAddressPublicly?: boolean | null;
  /**
   * Public buyer-page street address for deal cards, forms, and map context.
   */
  exactAddress?: string | null;
  /**
   * Exact map pin coordinates. If blank, the public map falls back to a county-level pin.
   */
  mapLocation?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  propertyDetails?: {
    /**
     * What the property is. Controls which detail fields below apply.
     */
    propertyType?: ('single_family' | 'condo' | 'townhouse' | 'duplex' | 'multifamily' | 'land') | null;
    /**
     * Number of units (duplex / multifamily).
     */
    units?: number | null;
    beds?: number | null;
    baths?: number | null;
    sqft?: number | null;
    lotSize?: string | null;
    yearBuilt?: number | null;
    construction?: string | null;
    occupancy?: ('vacant' | 'occupied' | 'unknown') | null;
  };
  /**
   * Public UI should hide calculated values when inputs are missing; helper calculations live in src/lib/deals/financials.ts.
   */
  financials?: {
    askingPrice?: number | null;
    arv?: number | null;
    estimatedRehab?: number | null;
    estimatedClosingCosts?: number | null;
    /**
     * Estimated market rent (monthly) for buy-and-hold / BRRRR buyers.
     */
    marketRent?: number | null;
    /**
     * Current in-place rent (monthly) if the property is occupied.
     */
    currentRent?: number | null;
    /**
     * Estimated cap rate (%). Leave blank to let the public UI compute from rent and price.
     */
    estCapRate?: number | null;
    potentialProfitOverride?: number | null;
    potentialROIOverride?: number | null;
    closedPrice?: number | null;
  };
  summary?: string | null;
  rehabScope?: string | null;
  /**
   * Buyer-facing condition note shown inside the expanded deal card.
   */
  conditionSummary?: string | null;
  /**
   * Buyer-facing comparable sale rows for the expanded deal card.
   */
  saleComps?:
    | {
        label: string;
        value: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Buyer-facing rental comp rows for the expanded deal card.
   */
  rentalComps?:
    | {
        label: string;
        value: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Quick highlight chips shown on the deal card and detail page.
   */
  featureTags?:
    | (
        | 'cash_only'
        | 'tenant_occupied'
        | 'cosmetic_reno'
        | 'full_gut'
        | 'owner_financing'
        | 'pool'
        | 'waterfront'
        | 'corner_lot'
        | 'new_roof'
      )[]
    | null;
  /**
   * Primary image shown on the deal card and detail hero. Falls back to the first gallery photo.
   */
  coverPhoto?: (number | null) | Media;
  photos?: (number | Media)[] | null;
  /**
   * Walkthrough video or 3D tour URL (YouTube, Matterport, etc.).
   */
  videoTourUrl?: string | null;
  disclaimer?: string | null;
  /**
   * Internal-only notes. Never include in public helpers or evidence.
   */
  internalNotes?: string | null;
  closedAt?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets".
 */
export interface Market {
  id: number;
  name: string;
  slug: string;
  county: 'miami_dade' | 'broward' | 'palm_beach' | 'other';
  sortOrder?: number | null;
  enabled?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  surface: 'seller' | 'buyer' | 'shared';
  status: 'draft' | 'published' | 'archived';
  sortOrder?: number | null;
  relatedPage?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  label: string;
  surface: 'seller' | 'buyer' | 'shared';
  /**
   * Only public settings are returned to unauthenticated frontend reads.
   */
  isPublic?: boolean | null;
  navigation?:
    | {
        label: string;
        href: string;
        surface: 'seller' | 'buyer' | 'shared';
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  footerDisclaimer?: string | null;
  /**
   * Display-only contact label. Do not store credentials or private alert destinations here.
   */
  publicContactLabel?: string | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  seoDefaults?: {
    title?: string | null;
    description?: string | null;
    openGraphImage?: (number | null) | Media;
  };
  /**
   * Operational destinations are configured through AWS Secrets Manager/env vars in later slices; no secrets belong in Payload content.
   */
  alerting?: {
    dealInterestAlertsEnabled?: boolean | null;
    /**
     * Non-secret routing note only. Do not enter webhook URLs, credentials, email addresses, or phone numbers.
     */
    routingNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-signups".
 */
export interface BuyerSignup {
  id: number;
  /**
   * S3-first source-of-truth object key. Mirror rows are written only after S3 persistence succeeds.
   */
  s3ObjectKey: string;
  submittedAt: string;
  email: string;
  /**
   * Non-PII hash used for dedupe/S3 keying; raw PII must not appear in logs/evidence.
   */
  emailHash?: string | null;
  fullName?: string | null;
  phone?: string | null;
  buyerType?: ('cash_buyer' | 'financed_buyer' | 'agent' | 'other') | null;
  areas?: (number | Market)[] | null;
  propertyTypes?: ('single_family' | 'multifamily' | 'condo_townhome' | 'land')[] | null;
  priceRange?: string | null;
  purchaseMethod?: ('cash' | 'hard_money' | 'financing' | 'undecided') | null;
  source: 'deals-website' | 'buyer-list';
  serviceConsent?: boolean | null;
  marketingConsent?: boolean | null;
  /**
   * Explicit SMS consent only. Must never be pre-checked on public forms.
   */
  smsConsent?: boolean | null;
  consentTimestamp?: string | null;
  s3FirstStatus: 's3_persisted' | 'mirror_repair_needed';
  ghlSyncStatus?: ('not_attempted' | 'queued' | 'succeeded' | 'failed') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-interest".
 */
export interface DealInterest {
  id: number;
  /**
   * S3-first source-of-truth object key. Mirror rows and alerts are created only after S3 persistence succeeds.
   */
  s3ObjectKey: string;
  deal?: (number | null) | Deal;
  dealSlug: string;
  submittedAt: string;
  email: string;
  /**
   * Non-PII hash for idempotency/dedupe and S3 keying.
   */
  emailHash?: string | null;
  fullName?: string | null;
  phone?: string | null;
  message?: string | null;
  source: 'deals-website';
  s3FirstStatus: 's3_persisted' | 'mirror_repair_needed';
  ghlSyncStatus?: ('not_attempted' | 'queued' | 'succeeded' | 'failed') | null;
  alertStatus?: ('not_attempted' | 'queued' | 'sent' | 'failed') | null;
  /**
   * No raw email/phone/full contact details. Slack/email alert implementation belongs to later slices.
   */
  redactedAlertSummary?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'markets';
        value: number | Market;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'buyer-signups';
        value: number | BuyerSignup;
      } | null)
    | ({
        relationTo: 'deal-interest';
        value: number | DealInterest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  accessPolicy?: T;
  mediaStatus?: T;
  containsExactAddressOrPrivateDetails?: T;
  referencedBy?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "markets_select".
 */
export interface MarketsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  county?: T;
  sortOrder?: T;
  enabled?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  surface?: T;
  status?: T;
  summary?: T;
  sections?:
    | T
    | {
        sectionType?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
        sortOrder?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        showInNav?: T;
        navLabel?: T;
        sortOrder?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  surface?: T;
  status?: T;
  sortOrder?: T;
  relatedPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  bestUse?: T;
  websiteVisibility?: T;
  dealStatus?: T;
  market?: T;
  area?: T;
  city?: T;
  county?: T;
  zip?: T;
  showExactAddressPublicly?: T;
  exactAddress?: T;
  mapLocation?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  propertyDetails?:
    | T
    | {
        propertyType?: T;
        units?: T;
        beds?: T;
        baths?: T;
        sqft?: T;
        lotSize?: T;
        yearBuilt?: T;
        construction?: T;
        occupancy?: T;
      };
  financials?:
    | T
    | {
        askingPrice?: T;
        arv?: T;
        estimatedRehab?: T;
        estimatedClosingCosts?: T;
        marketRent?: T;
        currentRent?: T;
        estCapRate?: T;
        potentialProfitOverride?: T;
        potentialROIOverride?: T;
        closedPrice?: T;
      };
  summary?: T;
  rehabScope?: T;
  conditionSummary?: T;
  saleComps?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  rentalComps?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  featureTags?: T;
  coverPhoto?: T;
  photos?: T;
  videoTourUrl?: T;
  disclaimer?: T;
  internalNotes?: T;
  closedAt?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  label?: T;
  surface?: T;
  isPublic?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        surface?: T;
        sortOrder?: T;
        id?: T;
      };
  footerDisclaimer?: T;
  publicContactLabel?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  seoDefaults?:
    | T
    | {
        title?: T;
        description?: T;
        openGraphImage?: T;
      };
  alerting?:
    | T
    | {
        dealInterestAlertsEnabled?: T;
        routingNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-signups_select".
 */
export interface BuyerSignupsSelect<T extends boolean = true> {
  s3ObjectKey?: T;
  submittedAt?: T;
  email?: T;
  emailHash?: T;
  fullName?: T;
  phone?: T;
  buyerType?: T;
  areas?: T;
  propertyTypes?: T;
  priceRange?: T;
  purchaseMethod?: T;
  source?: T;
  serviceConsent?: T;
  marketingConsent?: T;
  smsConsent?: T;
  consentTimestamp?: T;
  s3FirstStatus?: T;
  ghlSyncStatus?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-interest_select".
 */
export interface DealInterestSelect<T extends boolean = true> {
  s3ObjectKey?: T;
  deal?: T;
  dealSlug?: T;
  submittedAt?: T;
  email?: T;
  emailHash?: T;
  fullName?: T;
  phone?: T;
  message?: T;
  source?: T;
  s3FirstStatus?: T;
  ghlSyncStatus?: T;
  alertStatus?: T;
  redactedAlertSummary?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}